Rework clang-tidy integration

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -22,7 +22,7 @@ jobs:
     - name: Install dependencies
       run: |
         sudo apt update
-        sudo apt install -y cmake g++ libopencv-dev make
+        sudo apt install -y cmake g++ libopencv-dev make clang-tidy
 
     - name: Build directory
       run: mkdir build
@@ -30,8 +30,13 @@ jobs:
     - name: Run CMake
       run: cmake -S . -B build
 
+    # If you know how to get cmake to fail the build if clang-tidy exists non-zero please tell me
     - name: Build project
-      run: cmake --build build
+      run: |
+        cmake --build build 2>&1 | tee build.log
+        if grep -Eq 'warning:|error:' build.log; then
+            exit 1
+        fi
 
     - name: Run tests
       working-directory: ./build
